import '../../features/opportunities/data/models/opportunity_model.dart';
import '../../features/startups/data/models/startup_model.dart';
import '../../features/applications/data/models/application_model.dart';
import '../../features/notifications/data/models/notification_model.dart';

class DemoData {
  DemoData._();

  static final List<StartupModel> startups = [
    StartupModel(
      id: 'demo-startup-1',
      ownerId: 'demo-owner-1',
      name: 'NexEd Solutions',
      tagline: 'Reimagining access to quality education across Africa',
      description:
          'NexEd is an edtech startup building adaptive learning tools for secondary and tertiary students in Sub-Saharan Africa. We use AI to personalize study plans and bridge gaps in curriculum delivery.',
      industry: 'Education',
      verificationStatus: 'approved',
      teamSize: ['4-8'],
      focusAreas: ['Software Development', 'UI/UX Design', 'Content Creation', 'Marketing'],
      stage: 'growth',
      foundedAt: DateTime(2023, 3, 15),
      createdAt: DateTime(2023, 3, 15),
      updatedAt: DateTime.now(),
      opportunitiesCount: 3,
      followersCount: 47,
      isActive: true,
    ),
    StartupModel(
      id: 'demo-startup-2',
      ownerId: 'demo-owner-2',
      name: 'AgroLink Rwanda',
      tagline: 'Connecting smallholder farmers to premium markets',
      description:
          'AgroLink is a B2B agri-tech marketplace helping Rwandan farmers sell directly to supermarkets, hotels, and exporters. We cut out middlemen and increase farmer income by 40% on average.',
      industry: 'Agriculture',
      verificationStatus: 'approved',
      teamSize: ['1-3'],
      focusAreas: ['Business Development', 'Operations', 'Marketing', 'Research & Analysis'],
      stage: 'mvp',
      foundedAt: DateTime(2024, 1, 8),
      createdAt: DateTime(2024, 1, 8),
      updatedAt: DateTime.now(),
      opportunitiesCount: 2,
      followersCount: 23,
      isActive: true,
    ),
    StartupModel(
      id: 'demo-startup-3',
      ownerId: 'demo-owner-3',
      name: 'MindBridge Health',
      tagline: 'Mental wellness for African university students',
      description:
          'MindBridge offers anonymous peer-support and licensed therapist sessions via a mobile app, targeting the mental health crisis among African university students. We partner with 12 universities.',
      industry: 'Health & Wellness',
      verificationStatus: 'approved',
      teamSize: ['4-8'],
      focusAreas: ['Software Development', 'Community Management', 'Marketing', 'Research & Analysis'],
      stage: 'growth',
      foundedAt: DateTime(2022, 9, 1),
      createdAt: DateTime(2022, 9, 1),
      updatedAt: DateTime.now(),
      opportunitiesCount: 2,
      followersCount: 89,
      isActive: true,
    ),
    StartupModel(
      id: 'demo-startup-4',
      ownerId: 'demo-owner-4',
      name: 'PayEase Africa',
      tagline: 'Cross-border payments made simple for African SMEs',
      description:
          'PayEase enables SMEs to receive and send payments across 15 African countries in local currencies. We eliminate FX friction and reduce transfer fees from 8% to under 1.5%.',
      industry: 'Finance',
      verificationStatus: 'approved',
      teamSize: ['4-8'],
      focusAreas: ['Software Development', 'Finance', 'Business Development', 'Operations'],
      stage: 'scaling',
      foundedAt: DateTime(2022, 4, 12),
      createdAt: DateTime(2022, 4, 12),
      updatedAt: DateTime.now(),
      opportunitiesCount: 4,
      followersCount: 134,
      isActive: true,
    ),
  ];

  static final List<OpportunityModel> opportunities = [
    OpportunityModel(
      id: 'demo-opp-1',
      startupId: 'demo-startup-1',
      startupName: 'NexEd Solutions',
      startupVerified: true,
      title: 'Flutter Developer Intern',
      description:
          'Join our engineering team and help build the next version of our learning app used by 5,000+ students. You\'ll work directly with our CTO on new features, implement UI from Figma designs, and integrate our AI recommendation API.',
      type: 'Software Development',
      skills: ['Flutter', 'Firebase', 'Dart', 'REST APIs'],
      commitment: 'Part-time',
      duration: '3 months',
      isPaid: true,
      compensation: r'$150/month stipend',
      location: 'Remote',
      applicationDeadline: 14,
      deadline: DateTime.now().add(const Duration(days: 14)),
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      updatedAt: DateTime.now(),
      isActive: true,
      applicationCount: 12,
      viewCount: 89,
      responsibilities: [
        'Build and maintain Flutter mobile app features',
        'Integrate REST APIs and Firebase services',
        'Write clean, tested, and documented code',
        'Collaborate in weekly engineering sprints',
      ],
      requirements: [
        'Proficient in Flutter/Dart (personal projects count!)',
        'Understanding of state management (BLoC, Provider, or Riverpod)',
        'Ability to read and implement Figma designs',
        'Available for at least 15 hours/week',
      ],
      perks: 'Certificate of completion, potential equity consideration, mentorship from CTO, ALU reference letter',
      maxApplicants: 20,
    ),
    OpportunityModel(
      id: 'demo-opp-2',
      startupId: 'demo-startup-1',
      startupName: 'NexEd Solutions',
      startupVerified: true,
      title: 'UI/UX Design Intern',
      description:
          'Design intuitive learning experiences for African students. You\'ll conduct user research, create wireframes and prototypes in Figma, and run usability tests with real students at partner schools.',
      type: 'UI/UX Design',
      skills: ['Figma', 'User Research', 'Prototyping', 'Adobe XD'],
      commitment: 'Flexible',
      duration: '2 months',
      isPaid: false,
      location: 'Remote',
      applicationDeadline: 7,
      deadline: DateTime.now().add(const Duration(days: 7)),
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      updatedAt: DateTime.now(),
      isActive: true,
      applicationCount: 8,
      viewCount: 54,
      responsibilities: [
        'Conduct user research interviews with students',
        'Create wireframes, mockups, and interactive prototypes',
        'Design UI components for the NexEd app',
        'Run usability testing sessions',
      ],
      requirements: [
        'Proficient in Figma',
        'Portfolio demonstrating UX work',
        'Empathy-driven design thinking',
        'Good communication skills',
      ],
      perks: 'Build a portfolio with real impact, mentorship from product team, certificate',
      maxApplicants: 10,
    ),
    OpportunityModel(
      id: 'demo-opp-3',
      startupId: 'demo-startup-2',
      startupName: 'AgroLink Rwanda',
      startupVerified: true,
      title: 'Market Research Analyst Intern',
      description:
          'Help us understand the Rwandan agricultural supply chain. You\'ll interview farmers and buyers, analyze competitor pricing, and produce reports that directly shape our product roadmap.',
      type: 'Research & Analysis',
      skills: ['Market Research', 'Excel', 'Data Analysis', 'PowerPoint'],
      commitment: 'Part-time',
      duration: '2 months',
      isPaid: true,
      compensation: r'$80/month stipend',
      location: 'Hybrid',
      applicationDeadline: 10,
      deadline: DateTime.now().add(const Duration(days: 10)),
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      updatedAt: DateTime.now(),
      isActive: true,
      applicationCount: 5,
      viewCount: 31,
      responsibilities: [
        'Conduct field interviews with farmers in Kigali region',
        'Analyse competitor pricing data',
        'Produce weekly market intelligence reports',
        'Present findings to founding team',
      ],
      requirements: [
        'Strong analytical skills',
        'Comfortable with field interviews',
        'Proficient in Excel or Google Sheets',
        'Rwandan French or Kinyarwanda is a bonus',
      ],
      perks: r'$80/month stipend, field exposure, letter of recommendation',
      maxApplicants: 5,
    ),
    OpportunityModel(
      id: 'demo-opp-4',
      startupId: 'demo-startup-3',
      startupName: 'MindBridge Health',
      startupVerified: true,
      title: 'Community Manager Intern',
      description:
          'Grow and nurture our student mental wellness community across WhatsApp, Instagram, and our in-app community. You\'ll create weekly content, moderate conversations, and track engagement metrics.',
      type: 'Community Management',
      skills: ['Social Media', 'Copywriting', 'Community Management', 'Content Creation'],
      commitment: 'Flexible',
      duration: '3 months',
      isPaid: true,
      compensation: r'$100/month stipend',
      location: 'Remote',
      applicationDeadline: 20,
      deadline: DateTime.now().add(const Duration(days: 20)),
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      updatedAt: DateTime.now(),
      isActive: true,
      applicationCount: 19,
      viewCount: 102,
      responsibilities: [
        'Manage MindBridge Instagram, LinkedIn, and WhatsApp groups',
        'Create 3 content pieces per week (posts, reels, carousels)',
        'Run weekly community check-in sessions',
        'Track and report engagement metrics monthly',
      ],
      requirements: [
        'Passion for mental health advocacy',
        'Experience managing social media accounts',
        'Good writing and storytelling skills',
        'Consistent and reliable communicator',
      ],
      perks: r'$100/month stipend, mental wellness resources, certificate, strong LinkedIn recommendation',
      maxApplicants: 3,
    ),
    OpportunityModel(
      id: 'demo-opp-5',
      startupId: 'demo-startup-4',
      startupName: 'PayEase Africa',
      startupVerified: true,
      title: 'Backend Engineering Intern (Python/Django)',
      description:
          'Work on the core payment processing infrastructure at PayEase. You\'ll build REST APIs, optimize database queries, and implement webhook integrations with mobile money providers across Africa.',
      type: 'Software Development',
      skills: ['Python', 'Django', 'PostgreSQL', 'REST APIs', 'AWS'],
      commitment: 'Full-time',
      duration: '6 months',
      isPaid: true,
      compensation: r'$250/month stipend',
      location: 'Hybrid',
      applicationDeadline: 3,
      deadline: DateTime.now().add(const Duration(days: 3)),
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now(),
      isActive: true,
      applicationCount: 34,
      viewCount: 211,
      responsibilities: [
        'Build and maintain Django REST API endpoints',
        'Integrate with MTN, Airtel, and M-Pesa payment APIs',
        'Write unit and integration tests (minimum 80% coverage)',
        'Participate in code reviews and architecture discussions',
      ],
      requirements: [
        'Strong Python skills',
        'Experience with Django or FastAPI',
        'Familiarity with SQL databases',
        'Understanding of REST API design principles',
      ],
      perks:
          r'$250/month stipend + possible full-time offer, equity options, work with real fintech infrastructure processing $2M+ monthly',
      maxApplicants: 3,
    ),
  ];

  static final List<ApplicationModel> myApplications = [
    ApplicationModel(
      id: 'demo-app-1',
      opportunityId: 'demo-opp-1',
      opportunityTitle: 'Flutter Developer Intern',
      startupId: 'demo-startup-1',
      startupName: 'NexEd Solutions',
      applicantId: 'demo-student-1',
      applicantName: 'Demo Student',
      applicantEmail: 'demo@alustudent.com',
      coverLetter: 'I am passionate about Flutter and have built 3 personal projects...',
      status: 'shortlisted',
      skills: ['Flutter', 'Firebase', 'Dart'],
      appliedAt: DateTime.now().subtract(const Duration(days: 5)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      statusNote: 'Great portfolio! We\'d love to move you to the next stage.',
    ),
    ApplicationModel(
      id: 'demo-app-2',
      opportunityId: 'demo-opp-4',
      opportunityTitle: 'Community Manager Intern',
      startupId: 'demo-startup-3',
      startupName: 'MindBridge Health',
      applicantId: 'demo-student-1',
      applicantName: 'Demo Student',
      applicantEmail: 'demo@alustudent.com',
      coverLetter: 'Mental health is a topic I care deeply about...',
      status: 'pending',
      skills: ['Social Media', 'Copywriting'],
      appliedAt: DateTime.now().subtract(const Duration(days: 2)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    ApplicationModel(
      id: 'demo-app-3',
      opportunityId: 'demo-opp-3',
      opportunityTitle: 'Market Research Analyst Intern',
      startupId: 'demo-startup-2',
      startupName: 'AgroLink Rwanda',
      applicantId: 'demo-student-1',
      applicantName: 'Demo Student',
      applicantEmail: 'demo@alustudent.com',
      coverLetter: 'My research experience includes...',
      status: 'interviewing',
      skills: ['Market Research', 'Excel'],
      appliedAt: DateTime.now().subtract(const Duration(days: 12)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
      interviewDate: DateTime.now().add(const Duration(days: 2)),
      statusNote: 'Interview scheduled for July 3 at 10:00 AM EAT via Google Meet.',
    ),
  ];

  static final List<NotificationModel> notifications = [
    NotificationModel(
      id: 'notif-1',
      userId: 'demo-student-1',
      title: 'You\'ve been shortlisted',
      body: 'NexEd Solutions shortlisted you for Flutter Developer Intern. Check your application for details.',
      type: NotificationType.applicationStatusUpdate,
      referenceId: 'demo-app-1',
      isRead: false,
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    ),
    NotificationModel(
      id: 'notif-2',
      userId: 'demo-student-1',
      title: 'Interview scheduled',
      body: 'AgroLink Rwanda has scheduled an interview with you for Market Research Analyst Intern on July 3.',
      type: NotificationType.interviewScheduled,
      referenceId: 'demo-app-3',
      isRead: false,
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
    ),
    NotificationModel(
      id: 'notif-3',
      userId: 'demo-student-1',
      title: 'New opportunity match',
      body: 'PayEase Africa posted a Backend Engineering role matching your Flutter & Python skills.',
      type: NotificationType.newOpportunity,
      referenceId: 'demo-opp-5',
      isRead: true,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    NotificationModel(
      id: 'notif-4',
      userId: 'demo-student-1',
      title: 'Application received',
      body: 'MindBridge Health received your application for Community Manager Intern.',
      type: NotificationType.applicationReceived,
      referenceId: 'demo-app-2',
      isRead: true,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
  ];
}
