// This file is generated by FlutterFire CLI.
// Run: flutterfire configure --project=alu-nexus-xxxxx
// Replace the placeholder values below with your actual Firebase config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions is not supported for this platform.',
        );
    }
  }

  // TODO: Replace with actual Firebase project config values from Firebase Console
  // Project: alu-nexus
  // Steps:
  //   1. Create Firebase project at console.firebase.google.com
  //   2. Enable Authentication (Email/Password)
  //   3. Enable Firestore Database (production mode)
  //   4. Enable Firebase Storage
  //   5. Add Android app (package: com.alu.alu_nexus)
  //   6. Add iOS app (bundle: com.alu.aluNexus)
  //   7. Download google-services.json → android/app/
  //   8. Download GoogleService-Info.plist → ios/Runner/
  //   9. Run: dart pub global activate flutterfire_cli
  //  10. Run: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFkgO5Pu4k16t4vQaXAMkHQvnOSufKVqg',
    appId: '1:790288149422:android:69a2059193c957faf6763f',
    messagingSenderId: '790288149422',
    projectId: 'alunexus-b85a1',
    storageBucket: 'alunexus-b85a1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: '1:REPLACE_APP_ID:ios:REPLACE_HASH',
    messagingSenderId: 'REPLACE_SENDER_ID',
    projectId: 'alu-nexus',
    storageBucket: 'alu-nexus.appspot.com',
    iosClientId: 'REPLACE_IOS_CLIENT_ID',
    iosBundleId: 'com.alu.aluNexus',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNDgQM-8uEr2oQDs5cRkNLMCIeqjQYIyw',
    appId: '1:790288149422:web:c1d39603f58e931bf6763f',
    messagingSenderId: '790288149422',
    projectId: 'alunexus-b85a1',
    authDomain: 'alunexus-b85a1.firebaseapp.com',
    storageBucket: 'alunexus-b85a1.firebasestorage.app',
  );
}
